%% Import data from text file.
% Script for importing data from the following text file:
%
%    D:\present_projects\HIPC\analysis\results\result_onion_accuracy_test_mean.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2015/10/03 05:29:42

%% Initialize variables.
filename = 'D:\present_projects\HIPC\analysis\results\result_onion_accuracy_test_mean.csv';
delimiter = ',';
startRow = 2;

%% Read columns of data as strings:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric strings to numbers.
% Replace non-numeric strings with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = dataArray{col};
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[1,2]
    % Converts strings in the input cell array to numbers. Replaced non-numeric
    % strings with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1);
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData{row}, regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if any(numbers==',');
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(thousandsRegExp, ',', 'once'));
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric strings to numbers.
            if ~invalidThousandsSeparator;
                numbers = textscan(strrep(numbers, ',', ''), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch me
        end
    end
end


%% Allocate imported array to column variable names
VarName1 = cell2mat(raw(:, 1));
x = cell2mat(raw(:, 2));


%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans raw col numericData rawData row regexstr result numbers invalidThousandsSeparator thousandsRegExp me;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%SAinyam Data Done inbto
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%resultonionaccuracytestmean
%N = size(resultonionaccuracytestmean(:,1));
%u = [resultonionaccuracytestmean(int32(1:N),1),resultonionaccuracytestmean(int32(1:N),2)];
net = newff(VarName1,x, 5, {},'trainbr');
net.layers{1}.transferFcn = 'tansig';
y_train_sim = sim(net, VarName1);
hold on;
plot(y_train_sim,'r','LineWidth',1.75);
hold off;
net = train(net,VarName1,x);
[y_train_sim1, pf] = sim(net, VarName1);
figure, plot(x);
hold on;
plot(y_train_sim1,'r','LineWidth',1.75);
hold off;
diff = abs(x-y_train_sim1)
max(diff)
min(diff)
d=mean(diff)/mean(x);