%% Import data from text file.
% Script for importing data from the following text file:
%
%    D:\present_projects\HIPC\analysis\data\data_Onion.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2015/10/03 05:41:14

%% Initialize variables.
filename = 'D:\present_projects\HIPC\analysis\data\data_Onion.csv';
delimiter = ',';
startRow = 76;
endRow = 228;

%% Format string for each line of text:
%   column1: text (%s)
%	column5: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%*s%*s%*s%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow-startRow+1, 'Delimiter', delimiter, 'HeaderLines', startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
TimeSeries = dataArray{:, 1};
Price = dataArray{:, 2};


%% Clear temporary variables
clearvars filename delimiter startRow endRow formatSpec fileID dataArray ans;




%%%%%%%%%%%%%%%%%%%%%%%Done getting the data SAinyam says
rng1=(1:153)';
x_train=rng1;
net = newff(x_train,Price, 10, {},'trainbr');
net.layers{1}.transferFcn = 'tansig';
net.layers{2}.transferFcn = 'logsig';
y_train_sim = sim(net, x_train);


hold on;
plot(y_train_sim,'r','LineWidth',1.75);
hold off;
net = train(net,x_train,Price);
[y_train_sim1, pf] = sim(net, x_train);
figure, plot(Price);
hold on;
plot(y_train_sim1,'r','LineWidth',1.75);
hold off;
diff = abs(Price-y_train_sim1)
max(diff)
min(diff)
d=mean(diff)/mean(Price);